steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dbt-service'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/dbt-service'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dbt-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dbt-service'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-secrets'
      - '/secrets/dbt-service-keyfile=dbt-service-keyfile:latest'

images:
  - 'gcr.io/$PROJECT_ID/dbt-service'

options:
  logging: CLOUD_LOGGING_ONLY